name: gh-page

on: push

permissions: write-all

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: |
          cd docs && bun install
          pip install mdpo

      - name: Build
        run: |
          cd docs && bun run docs:build

      - name: Use html redirect
        run: |
          cat > ./docs/.vitepress/dist/index.html <<EOL
          <head>
            <meta http-equiv="refresh" content="0; url=zh/index.html">
          </head>
          EOL
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
